require 'json'

banks = [
  [
    "hello",
    "electronic",
    "rowbot",
    "yaaaaah",
    "harderrr",
    "faster",
    "better",
    "stronger",
    "teckno",
    "punqqck music",
    "hackerrr",
    "bayss",
    "runn",
    "drop it",
    "automate",
    "goodbuy"
  ],
  [
    "love",
    "help",
    "fire",
    "drop",
    "Rock",
    "dance",
    "fight",
    "kill",
    "you",
    "eye",
    "Baybee",
    "me",
    "together",
    "eye",
    "everybody",
    "the world"
  ],
  [
    "absolute zero",
    "acid",
    "amplitude",
    "combustion",
    "atomic",
    "chemical",
    "re action",
    "conductor",
    "electromagnet",
    "frequency",
    "lights",
    "concentration",
    "molecular",
    "newtron",
    "metal",
    "oxidize"
  ],
   [
    "freaks",
    "break stuff",
    "sea punk",
    "mathcore",
    "hardcore",
    "sell out",
    "anti establishment",
    "distortion",
    "wintermute",
    "frank zappa",
    "revolution",
    "straight edge",
    "socio political",
    "new wave",
    "enemy",
    "breathe"
  ],
]

phoneme_cache = "phonemes.json"

def load(filename)
  File.exist?(filename) ? JSON.parse(File.read(filename)) : {}
end

def save(filename, data)
  File.write(filename, data.to_json)
end

def generate_phoneme(word)
  return JSON.parse(`./parser #{word}`)
end

phonemes = load(phoneme_cache)

# build cache
banks.each_with_index do |words, bank_number|
  words.each do |word, word_number|
    if phonemes[word].nil?
      phonemes[word] = generate_phoneme(word)
    end
  end
end

save(phoneme_cache, phonemes)
wordpos = {}
index = 0

# generate data blob + indices
File.open("./wordlist.cc", 'w') do |file|
  file.write('''#include "wordlist.h"
// This file is autogenerated by running `ruby ./words/words.rb`

const unsigned char data[] = {
''')

  # output data
  banks.each_with_index do |words, bank_number|
    words.each do |word, word_number|
      wordpos[word] = index
      file.write(phonemes[word]['index'].join(", "))
      file.write(', ')
      file.write(phonemes[word]['length'].join(", "))
      file.write(', ')
      file.write(phonemes[word]['stress'].join(", "))
      file.write(', ')
      file.write "// #{word}\n"
      index += phonemes[word]['index'].count * 3
    end
  end
  file.write("};\n\n")

  file.write("const unsigned char wordlen[#{banks.count}][#{banks[0].count}] = {\n")
  banks.each_with_index do |bank, bank_number|
    file.write("{")
    file.write(bank.map { |word| phonemes[word]['index'].count }.join(', '))
    file.write("},\n")
  end
  file.write("};\n")

  file.write("const unsigned short wordpos[#{banks.count}][#{banks[0].count}] = {\n")
  banks.each_with_index do |bank, bank_number|
    file.write("{")
    file.write(bank.map { |word| wordpos[word] }.join(', '))
    file.write("},\n")
  end
  file.write("};\n")
end

# generate data blob + indices
File.open("./wordlist.h", 'w') do |file|
  file.write("""
#ifndef __WORDLIST_H__
#define __WORDLIST_H__

// This file is autogenerated by running `ruby ./words/words.rb`

extern const unsigned char data[];
extern const unsigned char wordlen[#{banks.count}][#{banks[0].count}];
extern const unsigned short wordpos[#{banks.count}][#{banks[0].count}];

#define NUM_BANKS #{banks.count}
#define NUM_WORDS #{banks[0].count}

#endif
""")
end
